### ISSUE TITLE
jump with camera direction

### ISSUE THREAD

**Issue by pantsgt** [majikayogames/SimpleFPSController#2]
what do i edit in the code to be able do this? i dont want to hold down movement keys to go in certain direction

**Comment by majikayogames** [comment]
This would require some custom code, maybe something like each frame when jumping, take the velocity XZ .length() and then create some vector rotated per the camera's basis, then take the XZ of that and multiply it by the velocity XZ length, and set the players air velocity per that.

Out of scope for this repo so I'll be closing this issue.
